apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  namespace: eladsopher
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-eladsopher  # Reference the StorageClass
  resources:
    requests:
      storage: 5Gi