apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.serviceName | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    app: {{ .Values.db.appLabel | quote }}
  ports:
  - protocol: TCP
    port: {{ .Values.db.servicePort }}
    targetPort: {{ .Values.db.containerPort }}
  clusterIP: None  # Headless service for StatefulSet