apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name | quote }}
provisioner: {{ .Values.storageClass.provisioner | quote }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode | quote }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
parameters:
  type: {{ .Values.storageClass.parameters.type | quote }}
  fsType: {{ .Values.storageClass.parameters.fsType | quote }}
  encrypted: {{ .Values.storageClass.parameters.encrypted | quote }}