apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.serviceName | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    app: {{ .Values.wordpress.appLabel | quote }}
  ports:
  - protocol: TCP
    port: {{ .Values.wordpress.servicePort }}
    targetPort: {{ .Values.wordpress.containerPort }}
  type: ClusterIP