# monitor-values.yaml
prometheus-node-exporter:
  service:
    port: 9155
    targetPort: 9155
    type: ClusterIP  # Avoid NodePort
  containerPort: 9155
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

prometheus:
  prometheusSpec:
    service:
      port: 9095  # Shifted from 9090
      type: ClusterIP
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

grafana:
  service:
    root_url:
      afd291ea56b0e40d9aba85bc4ac72707-1219273054.us-east-1.elb.amazonaws.com/grafana
    serve_from_sub_path: true